/* GENERATED by apps/web/scripts/build-demo-data.py — do not edit by hand.
 * Demo evidence logs assembled from fixtures/slack/*.json, fixtures/SHA256SUMS
 * and contracts/examples/*.json. Card contents and every number are copied
 * from those files; only event ids and timestamps are synthetic.
 */
import type { EvidenceEvent } from "agent-core/shared";

export type DemoScenario = {
  id: string;
  title: string;
  channel: string;
  channel_id: string;
  fixture: string;
  kind: "scenario" | "control";
  summary: string;
  events: EvidenceEvent[];
};

export const ENGINEERS = ["Dara Voss", "Tam Holloway", "Juno Marsh", "Milo Trent", "Ines Calder"] as const;

export const SCENARIOS: DemoScenario[] = [
  {
    "id": "scenario-a",
    "title": "Precharge RC timing",
    "channel": "#ks4-electrical",
    "channel_id": "C00SYN01",
    "fixture": "scenario-a.json",
    "kind": "scenario",
    "summary": "Text says 680 uF, diagram says 750 uF; then the bus becomes 820 uF and the relay timer is violated.",
    "events": [
      {
        "event_id": "ev-1787062320000100-0001",
        "at": "2026-08-19T18:05:10Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787064000.000500",
        "kind": "silence",
        "reason": "gate_closed"
      },
      {
        "event_id": "ev-1787062320000100-0002",
        "at": "2026-08-19T18:05:12Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "message_read",
        "ts": "1787062320.000100",
        "from": "Dara Voss",
        "is_bot": false,
        "text": "Precharge board r2 review doc is up. Dropped one film cap, bus is now 680 uF.",
        "is_change": true
      },
      {
        "event_id": "ev-1787062320000100-0003",
        "at": "2026-08-19T18:05:14Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "message_read",
        "ts": "1787064000.000500",
        "from": "Tam Holloway",
        "is_bot": false,
        "text": "Relay close timer in firmware is 2.5 s, matches the doc.",
        "is_change": false
      },
      {
        "event_id": "ev-1787062320000100-0004",
        "at": "2026-08-19T18:05:16Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "message_read",
        "ts": "1787166300.000600",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer can you check section 3 of the r2 doc before I sign the review?",
        "is_change": false
      },
      {
        "event_id": "ev-1787062320000100-0005",
        "at": "2026-08-19T18:05:18Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "document_read",
        "document": "precharge-review-r2.docx",
        "revision": "r2",
        "sha256": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282",
        "line_count": 13,
        "named_in_ts": "1787062320.000100"
      },
      {
        "event_id": "ev-1787062320000100-0006",
        "at": "2026-08-19T18:05:20Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "check_run",
        "run_id": "rc-20260912T151200Z-7f3a",
        "checker": "rc",
        "version": "1",
        "inputs": {
          "R_ohm": 470,
          "threshold": 0.999,
          "timer_s": 2.5,
          "capacitances": [
            {
              "label": "680uF_text",
              "C_F": 0.00068
            },
            {
              "label": "750uF_diagram",
              "C_F": 0.00075
            },
            {
              "label": "820uF_change",
              "C_F": 0.00082
            },
            {
              "label": "2mF_example",
              "C_F": 0.002
            }
          ],
          "printed": [
            {
              "label": "printed_2.435",
              "value_s": 2.435,
              "against": [
                "680uF_text",
                "750uF_diagram"
              ]
            },
            {
              "label": "printed_6.91",
              "value_s": 6.91,
              "against": [
                "2mF_example"
              ]
            }
          ],
          "tolerance_s": 0.0005
        },
        "outputs": {
          "per_capacitance": {
            "680uF_text": {
              "RC_s": 0.3196,
              "t_threshold_s": 2.2077,
              "fraction_at_timer": 0.9996
            },
            "750uF_diagram": {
              "RC_s": 0.3525,
              "t_threshold_s": 2.435,
              "fraction_at_timer": 0.99917
            },
            "820uF_change": {
              "RC_s": 0.3854,
              "t_threshold_s": 2.6622,
              "fraction_at_timer": 0.99848
            },
            "2mF_example": {
              "RC_s": 0.94,
              "t_threshold_s": 6.4933,
              "fraction_at_timer": 0.93002
            }
          }
        },
        "error": null,
        "checks": [
          {
            "name": "printed_2.435_matches_680uF_text",
            "pass": false,
            "expected": 2.435,
            "actual": 2.2077
          },
          {
            "name": "printed_2.435_matches_750uF_diagram",
            "pass": true,
            "expected": 2.435,
            "actual": 2.435
          },
          {
            "name": "printed_6.91_matches_2mF_example",
            "pass": false,
            "expected": 6.91,
            "actual": 6.4933
          },
          {
            "name": "680uF_text_reaches_threshold_by_timer",
            "pass": true,
            "expected": 0.999,
            "actual": 0.9996
          },
          {
            "name": "750uF_diagram_reaches_threshold_by_timer",
            "pass": true,
            "expected": 0.999,
            "actual": 0.99917
          },
          {
            "name": "820uF_change_reaches_threshold_by_timer",
            "pass": false,
            "expected": 0.999,
            "actual": 0.99848
          },
          {
            "name": "2mF_example_reaches_threshold_by_timer",
            "pass": false,
            "expected": 0.999,
            "actual": 0.93002
          }
        ],
        "evidence_refs": [
          {
            "kind": "document",
            "id": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282"
          },
          {
            "kind": "document",
            "id": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282"
          },
          {
            "kind": "message",
            "id": "1787062320.000100"
          }
        ]
      },
      {
        "event_id": "ev-1787062320000100-0007",
        "at": "2026-08-19T18:05:22Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "finding_published",
        "finding": {
          "finding_id": "fnd-a-r2-001",
          "status": "live",
          "requirements_revision": "1787062320.000100",
          "discrepancy": "Section 3 text states C = 680 uF; the section 2 diagram caption states 750 uF. The printed t_99.9 = 2.435 s reproduces only with 750 uF. With 680 uF, t_99.9 = 2.208 s. Section 4 prints 6.91 s for a 2 mF bank; recomputed value is 6.493 s.",
          "why_it_matters": "The relay close timer of 2.5 s keeps positive margin either way (65 ms at 750 uF, 292 ms at 680 uF), but the document's stated basis is not the value it computed from, so the review cannot be signed against it.",
          "sources": [
            {
              "kind": "document",
              "id": "precharge-review-r2.docx",
              "revision": "r2",
              "sha256": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282",
              "locator": "section 2, diagram caption",
              "quote": "Bus capacitance C = 750 uF (3 x 250 uF film)."
            },
            {
              "kind": "document",
              "id": "precharge-review-r2.docx",
              "revision": "r2",
              "sha256": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282",
              "locator": "section 3, line 2",
              "quote": "t_99.9 = -470 * 750e-6 * ln(0.001) = 2.435 s."
            },
            {
              "kind": "message",
              "id": "1787062320.000100",
              "quote": "Dropped one film cap, bus is now 680 uF."
            }
          ],
          "reproduced": [
            {
              "label": "t_99.9 at 680 uF",
              "computed": 2.2077,
              "unit": "s",
              "printed": 2.435,
              "matches": false,
              "tolerance": 0.0005
            },
            {
              "label": "t_99.9 at 750 uF",
              "computed": 2.435,
              "unit": "s",
              "printed": 2.435,
              "matches": true,
              "tolerance": 0.0005
            },
            {
              "label": "t_99.9 at 2 mF",
              "computed": 6.4933,
              "unit": "s",
              "printed": 6.91,
              "matches": false,
              "tolerance": 0.0005
            }
          ],
          "inferred": [],
          "resolution": "Dara confirms whether the bus is 680 or 750 uF and corrects the diagram or the text. Section 4 needs a corrected printed value regardless.",
          "question": {
            "to": "Dara Voss",
            "ask": "Is the r2 bus capacitance 680 uF (section 3 text) or 750 uF (section 2 diagram)?"
          },
          "checker_run": {
            "checker": "rc",
            "version": "1",
            "run_id": "rc-20260912T151200Z-7f3a"
          }
        }
      },
      {
        "event_id": "ev-1787062320000100-0008",
        "at": "2026-08-19T19:30:24Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "message_read",
        "ts": "1787062320.000100",
        "from": "Dara Voss",
        "is_bot": false,
        "text": "Precharge board r2 review doc is up. Dropped one film cap, bus is now 680 uF.",
        "is_change": true
      },
      {
        "event_id": "ev-1787062320000100-0009",
        "at": "2026-08-19T19:30:26Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "message_read",
        "ts": "1787064000.000500",
        "from": "Tam Holloway",
        "is_bot": false,
        "text": "Relay close timer in firmware is 2.5 s, matches the doc.",
        "is_change": false
      },
      {
        "event_id": "ev-1787062320000100-0010",
        "at": "2026-08-19T19:30:28Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "message_read",
        "ts": "1787166300.000600",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer can you check section 3 of the r2 doc before I sign the review?",
        "is_change": false
      },
      {
        "event_id": "ev-1787062320000100-0011",
        "at": "2026-08-19T19:30:30Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "message_read",
        "ts": "1787171400.000200",
        "from": "Dara Voss",
        "is_bot": false,
        "text": "Correction: we are adding a 140 uF snubber bank on the motor controller side. Bus is 820 uF, not 680. Doc will be r3.",
        "is_change": true
      },
      {
        "event_id": "ev-1787062320000100-0012",
        "at": "2026-08-19T19:30:32Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "document_read",
        "document": "precharge-review-r2.docx",
        "revision": "r2",
        "sha256": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282",
        "line_count": 13,
        "named_in_ts": "1787062320.000100"
      },
      {
        "event_id": "ev-1787062320000100-0013",
        "at": "2026-08-19T19:30:34Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "check_run",
        "checker": "rc",
        "version": "1",
        "inputs": {
          "R_ohm": 470,
          "threshold": 0.999,
          "timer_s": 2.5,
          "capacitances": [
            {
              "label": "680uF_text",
              "C_F": 0.00068
            },
            {
              "label": "750uF_diagram",
              "C_F": 0.00075
            },
            {
              "label": "820uF_change",
              "C_F": 0.00082
            },
            {
              "label": "2mF_example",
              "C_F": 0.002
            }
          ],
          "printed": [
            {
              "label": "printed_2.435",
              "value_s": 2.435,
              "against": [
                "680uF_text",
                "750uF_diagram"
              ]
            },
            {
              "label": "printed_6.91",
              "value_s": 6.91,
              "against": [
                "2mF_example"
              ]
            }
          ],
          "tolerance_s": 0.0005
        },
        "outputs": {
          "per_capacitance": {
            "680uF_text": {
              "RC_s": 0.3196,
              "t_threshold_s": 2.2077,
              "fraction_at_timer": 0.9996
            },
            "750uF_diagram": {
              "RC_s": 0.3525,
              "t_threshold_s": 2.435,
              "fraction_at_timer": 0.99917
            },
            "820uF_change": {
              "RC_s": 0.3854,
              "t_threshold_s": 2.6622,
              "fraction_at_timer": 0.99848
            },
            "2mF_example": {
              "RC_s": 0.94,
              "t_threshold_s": 6.4933,
              "fraction_at_timer": 0.93002
            }
          }
        },
        "error": null,
        "checks": [
          {
            "name": "printed_2.435_matches_680uF_text",
            "pass": false,
            "expected": 2.435,
            "actual": 2.2077
          },
          {
            "name": "printed_2.435_matches_750uF_diagram",
            "pass": true,
            "expected": 2.435,
            "actual": 2.435
          },
          {
            "name": "printed_6.91_matches_2mF_example",
            "pass": false,
            "expected": 6.91,
            "actual": 6.4933
          },
          {
            "name": "680uF_text_reaches_threshold_by_timer",
            "pass": true,
            "expected": 0.999,
            "actual": 0.9996
          },
          {
            "name": "750uF_diagram_reaches_threshold_by_timer",
            "pass": true,
            "expected": 0.999,
            "actual": 0.99917
          },
          {
            "name": "820uF_change_reaches_threshold_by_timer",
            "pass": false,
            "expected": 0.999,
            "actual": 0.99848
          },
          {
            "name": "2mF_example_reaches_threshold_by_timer",
            "pass": false,
            "expected": 0.999,
            "actual": 0.93002
          }
        ],
        "run_id": "rc-20260912T153100Z-b21c",
        "evidence_refs": [
          {
            "kind": "message",
            "id": "1787171400.000400"
          },
          {
            "kind": "document",
            "id": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282"
          }
        ]
      },
      {
        "event_id": "ev-1787062320000100-0014",
        "at": "2026-08-19T19:30:36Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "finding_superseded",
        "finding_id": "fnd-a-r2-001",
        "superseded_by": "fnd-a-820-002",
        "cause_ts": "1787171400.000200"
      },
      {
        "event_id": "ev-1787062320000100-0015",
        "at": "2026-08-19T19:30:38Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787171400.000200",
        "kind": "finding_published",
        "finding": {
          "finding_id": "fnd-a-820-002",
          "status": "live",
          "supersedes": "fnd-a-r2-001",
          "requirements_revision": "1787171400.000400",
          "discrepancy": "Relay close timer 2.5 s is earlier than t_99.9 = 2.662 s at 820 uF. Bus reaches 99.85 percent at 2.5 s, short of the 99.9 percent criterion.",
          "why_it_matters": "With the 140 uF snubber bank the precharge does not meet its own completion criterion before the relay closes. Firmware timer or resistor value must change before r3 is signed.",
          "sources": [
            {
              "kind": "message",
              "id": "1787171400.000400",
              "quote": "Bus is 820 uF, not 680. Doc will be r3."
            },
            {
              "kind": "document",
              "id": "precharge-review-r2.docx",
              "revision": "r2",
              "sha256": "bef5a5dc15a5e31fbaaceb77e8150767f421e55c86e5c14db33f3b54eefbd282",
              "locator": "section 1",
              "quote": "Precharge resistor R = 470 ohm, 10 W."
            }
          ],
          "reproduced": [
            {
              "label": "t_99.9 at 820 uF",
              "computed": 2.6622,
              "unit": "s"
            },
            {
              "label": "fraction charged at 2.5 s, 820 uF",
              "computed": 0.99848,
              "unit": "ratio"
            }
          ],
          "inferred": [
            "R = 470 ohm is carried from r2 because r3 does not exist yet; this card is bound to the message, not a document."
          ],
          "resolution": "Raise the relay close timer above 2.662 s, or lower R, and publish r3 with the new C and printed result.",
          "checker_run": {
            "checker": "rc",
            "version": "1",
            "run_id": "rc-20260912T153100Z-b21c"
          }
        }
      }
    ]
  },
  {
    "id": "scenario-b",
    "title": "Stale simulation inputs",
    "channel": "#ks4-strategy-sim",
    "channel_id": "C00SYN02",
    "fixture": "scenario-b.json",
    "kind": "scenario",
    "summary": "Route request names the July 3 sheet after Milo said to use v2-1; feasibility flips between versions.",
    "events": [
      {
        "event_id": "ev-1786472100000800-0001",
        "at": "2026-08-11T17:15:06Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1783092000.000700",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Sim inputs v2-0 posted for the summer runs.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0002",
        "at": "2026-08-11T17:15:08Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1784929680.000300",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Found why last week's numbers looked optimistic: we were still on KS-3 mass and Crr.\nv2-1 has the post-suspension values (318 kg, Crr 0.0048). Use v2-1 for anything after today.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0003",
        "at": "2026-08-11T17:15:10Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1784930520.000400",
        "from": "Ines Calder",
        "is_bot": false,
        "text": "Confirmed, corner weights from Tuesday add up to 318 with driver.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0004",
        "at": "2026-08-11T17:15:12Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1786472100.000800",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer run the Northgate to Ferris segment (220 km, no optional loop), start SoC 96%, end SoC 40%, two 20-minute driver swaps, 22 m/s constant. I grabbed the params from the July 3 sheet.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0005",
        "at": "2026-08-11T17:15:14Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-0.xlsx",
        "revision": "v2-0",
        "sha256": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f",
        "line_count": 9,
        "named_in_ts": "1783092000.000700"
      },
      {
        "event_id": "ev-1786472100000800-0006",
        "at": "2026-08-11T17:15:16Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-1.xlsx",
        "revision": "v2-1",
        "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
        "line_count": 10,
        "named_in_ts": "1784929680.000300"
      },
      {
        "event_id": "ev-1786472100000800-0007",
        "at": "2026-08-11T17:15:18Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "check_run",
        "run_id": "route-20260912T161102Z-de45",
        "checker": "route",
        "version": "1",
        "inputs": {
          "v2-0": {
            "mass_kg": 290,
            "Crr": 0.004,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.4
          },
          "v2-1": {
            "mass_kg": 318,
            "Crr": 0.0048,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.4
          }
        },
        "outputs": {
          "budget, SoC 96 to 40 percent": {
            "computed": 2.912,
            "unit": "kWh"
          },
          "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-0665)": {
            "computed": 2.825,
            "unit": "kWh"
          },
          "energy at 22 m/s, v2-1 inputs": {
            "computed": 3.0447,
            "unit": "kWh"
          },
          "max feasible speed, v2-0 inputs (run route-20260912T161102Z-0665)": {
            "computed": 22.4448,
            "unit": "m/s"
          },
          "max feasible speed, v2-1 inputs": {
            "computed": 21.3037,
            "unit": "m/s"
          }
        },
        "checks": [
          {
            "name": "budget, SoC 96 to 40 percent",
            "pass": true,
            "actual": 2.912
          },
          {
            "name": "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-0665)",
            "pass": true,
            "actual": 2.825
          },
          {
            "name": "energy at 22 m/s, v2-1 inputs",
            "pass": true,
            "actual": 3.0447
          },
          {
            "name": "max feasible speed, v2-0 inputs (run route-20260912T161102Z-0665)",
            "pass": true,
            "actual": 22.4448
          },
          {
            "name": "max feasible speed, v2-1 inputs",
            "pass": true,
            "actual": 21.3037
          }
        ],
        "error": null,
        "evidence_refs": [
          {
            "kind": "message",
            "id": "1786472100.000800"
          },
          {
            "kind": "message",
            "id": "1784929680.000300"
          },
          {
            "kind": "message",
            "id": "1784930520.000400"
          },
          {
            "kind": "document",
            "id": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f"
          },
          {
            "kind": "document",
            "id": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4"
          }
        ]
      },
      {
        "event_id": "ev-1786472100000800-0008",
        "at": "2026-08-11T17:15:20Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "finding_published",
        "finding": {
          "finding_id": "fnd-b-40-001",
          "status": "live",
          "requirements_revision": "1786472100.000800",
          "discrepancy": "The request takes its parameters from the July 3 sheet (v2-0: 290 kg, Crr 0.0040). Milo's July 24 message names v2-1 (318 kg, Crr 0.0048) as the inputs for anything after that date, and Ines confirmed the 318 kg corner weights. At 22 m/s over 220 km with a 96 to 40 percent SoC budget of 2.912 kWh, v2-0 gives 2.825 kWh (feasible) and v2-1 gives 3.045 kWh (not feasible). The conclusion flips between the two input files.",
          "why_it_matters": "A feasibility answer posted from v2-0 would be wrong by 0.22 kWh, about 4 percent of the pack. Under v2-1 the largest constant speed that fits the budget is 21.30 m/s, not 22.",
          "sources": [
            {
              "kind": "message",
              "id": "1786472100.000800",
              "quote": "I grabbed the params from the July 3 sheet."
            },
            {
              "kind": "message",
              "id": "1784929680.000300",
              "quote": "v2-1 has the post-suspension values (318 kg, Crr 0.0048). Use v2-1 for anything after today."
            },
            {
              "kind": "message",
              "id": "1784930520.000400",
              "quote": "Confirmed, corner weights from Tuesday add up to 318 with driver."
            },
            {
              "kind": "document",
              "id": "ks4-sim-inputs-v2-0.xlsx",
              "revision": "v2-0",
              "sha256": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f",
              "locator": "sheet params, rows 2 to 5",
              "quote": "mass_kg 290, Crr 0.0040, CdA 0.12, pack_kWh 5.2"
            },
            {
              "kind": "document",
              "id": "ks4-sim-inputs-v2-1.xlsx",
              "revision": "v2-1",
              "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
              "locator": "sheet params, rows 2 to 5, and cell A8",
              "quote": "mass_kg 318, Crr 0.0048, CdA 0.12, pack_kWh 5.2. A8: mass and Crr updated after KS-4 suspension swap, see #ks4-suspension 2026-07-22."
            }
          ],
          "reproduced": [
            {
              "label": "budget, SoC 96 to 40 percent",
              "computed": 2.912,
              "unit": "kWh"
            },
            {
              "label": "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-0665)",
              "computed": 2.825,
              "unit": "kWh"
            },
            {
              "label": "energy at 22 m/s, v2-1 inputs",
              "computed": 3.0447,
              "unit": "kWh"
            },
            {
              "label": "max feasible speed, v2-0 inputs (run route-20260912T161102Z-0665)",
              "computed": 22.4448,
              "unit": "m/s"
            },
            {
              "label": "max feasible speed, v2-1 inputs",
              "computed": 21.3037,
              "unit": "m/s"
            }
          ],
          "inferred": [
            "The optional loop is excluded and the two 20-minute swaps are the full swap budget, both taken from the request text as written.",
            "Array input is assumed zero. The model is constant-speed rolling plus aero only.",
            "Driving time at 22 m/s is 2.778 h, plus 40 min of swaps gives 3.44 h wall time. Not recomputed by the checker."
          ],
          "resolution": "Juno confirms the run should use v2-1, or Milo states v2-0 is intentionally being used for a KS-3 comparison. The v2-1 result above is posted but the run is blocked on that confirmation, not final.",
          "question": {
            "to": "Juno Marsh",
            "ask": "Should this run use v2-1 (July 24, 318 kg, Crr 0.0048) instead of the July 3 sheet? Milo's July 24 message supersedes v2-0 for anything after that date."
          },
          "checker_run": {
            "checker": "route",
            "version": "1",
            "run_id": "route-20260912T161102Z-de45"
          }
        }
      },
      {
        "event_id": "ev-1786472100000800-0009",
        "at": "2026-08-11T18:00:22Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1783092000.000700",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Sim inputs v2-0 posted for the summer runs.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0010",
        "at": "2026-08-11T18:00:24Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1784929680.000300",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Found why last week's numbers looked optimistic: we were still on KS-3 mass and Crr.\nv2-1 has the post-suspension values (318 kg, Crr 0.0048). Use v2-1 for anything after today.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0011",
        "at": "2026-08-11T18:00:26Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1784930520.000400",
        "from": "Ines Calder",
        "is_bot": false,
        "text": "Confirmed, corner weights from Tuesday add up to 318 with driver.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0012",
        "at": "2026-08-11T18:00:28Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1786472100.000800",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer run the Northgate to Ferris segment (220 km, no optional loop), start SoC 96%, end SoC 40%, two 20-minute driver swaps, 22 m/s constant. I grabbed the params from the July 3 sheet.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0013",
        "at": "2026-08-11T18:00:30Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1786474920.000900",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Race director allows end SoC 35% for this segment now, not 40%.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0014",
        "at": "2026-08-11T18:00:32Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-0.xlsx",
        "revision": "v2-0",
        "sha256": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f",
        "line_count": 9,
        "named_in_ts": "1783092000.000700"
      },
      {
        "event_id": "ev-1786472100000800-0015",
        "at": "2026-08-11T18:00:34Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-1.xlsx",
        "revision": "v2-1",
        "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
        "line_count": 10,
        "named_in_ts": "1784929680.000300"
      },
      {
        "event_id": "ev-1786472100000800-0016",
        "at": "2026-08-11T18:00:36Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "check_run",
        "run_id": "route-20260912T161102Z-51cc",
        "checker": "route",
        "version": "1",
        "inputs": {
          "v2-0": {
            "mass_kg": 290,
            "Crr": 0.004,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.35
          },
          "v2-1": {
            "mass_kg": 318,
            "Crr": 0.0048,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.35
          }
        },
        "outputs": {
          "budget, SoC 96 to 35 percent": {
            "computed": 3.172,
            "unit": "kWh"
          },
          "energy at 22 m/s, v2-1 inputs": {
            "computed": 3.0447,
            "unit": "kWh"
          },
          "max feasible speed, v2-1 inputs": {
            "computed": 22.6481,
            "unit": "m/s"
          },
          "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-c40d)": {
            "computed": 2.825,
            "unit": "kWh"
          },
          "max feasible speed, v2-0 inputs (run route-20260912T161102Z-c40d)": {
            "computed": 23.7247,
            "unit": "m/s"
          }
        },
        "checks": [
          {
            "name": "budget, SoC 96 to 35 percent",
            "pass": true,
            "actual": 3.172
          },
          {
            "name": "energy at 22 m/s, v2-1 inputs",
            "pass": true,
            "actual": 3.0447
          },
          {
            "name": "max feasible speed, v2-1 inputs",
            "pass": true,
            "actual": 22.6481
          },
          {
            "name": "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-c40d)",
            "pass": true,
            "actual": 2.825
          },
          {
            "name": "max feasible speed, v2-0 inputs (run route-20260912T161102Z-c40d)",
            "pass": true,
            "actual": 23.7247
          }
        ],
        "error": null,
        "evidence_refs": [
          {
            "kind": "message",
            "id": "1786474920.000900"
          },
          {
            "kind": "message",
            "id": "1786472100.000800"
          },
          {
            "kind": "message",
            "id": "1784929680.000300"
          },
          {
            "kind": "document",
            "id": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4"
          }
        ]
      },
      {
        "event_id": "ev-1786472100000800-0017",
        "at": "2026-08-11T18:00:38Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "finding_superseded",
        "finding_id": "fnd-b-40-001",
        "superseded_by": "fnd-b-35-002",
        "cause_ts": "1786474920.000900"
      },
      {
        "event_id": "ev-1786472100000800-0018",
        "at": "2026-08-11T18:00:40Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "finding_published",
        "finding": {
          "finding_id": "fnd-b-35-002",
          "status": "live",
          "supersedes": "fnd-b-40-001",
          "requirements_revision": "1786474920.000900",
          "discrepancy": "With end SoC 35 percent the budget is 3.172 kWh. At 22 m/s over 220 km, v2-1 gives 3.045 kWh and v2-0 gives 2.825 kWh, so the segment is feasible under both input files and the conclusion no longer flips. The request still names the July 3 sheet; v2-1 remains the inputs Milo named for anything after July 24.",
          "why_it_matters": "The 40 percent card said 22 m/s did not fit under v2-1. That is no longer true at 35 percent, with 0.127 kWh of margin. The max constant speed under v2-1 rises from 21.30 to 22.65 m/s. The input-version choice still changes the margin by 0.22 kWh, so the run stays bound to v2-1.",
          "sources": [
            {
              "kind": "message",
              "id": "1786474920.000900",
              "quote": "Race director allows end SoC 35% for this segment now, not 40%."
            },
            {
              "kind": "message",
              "id": "1786472100.000800",
              "quote": "Northgate to Ferris segment (220 km, no optional loop), start SoC 96%"
            },
            {
              "kind": "message",
              "id": "1784929680.000300",
              "quote": "Use v2-1 for anything after today."
            },
            {
              "kind": "document",
              "id": "ks4-sim-inputs-v2-1.xlsx",
              "revision": "v2-1",
              "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
              "locator": "sheet params, rows 2 to 5",
              "quote": "mass_kg 318, Crr 0.0048, CdA 0.12, pack_kWh 5.2"
            }
          ],
          "reproduced": [
            {
              "label": "budget, SoC 96 to 35 percent",
              "computed": 3.172,
              "unit": "kWh"
            },
            {
              "label": "energy at 22 m/s, v2-1 inputs",
              "computed": 3.0447,
              "unit": "kWh"
            },
            {
              "label": "max feasible speed, v2-1 inputs",
              "computed": 22.6481,
              "unit": "m/s"
            },
            {
              "label": "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-c40d)",
              "computed": 2.825,
              "unit": "kWh"
            },
            {
              "label": "max feasible speed, v2-0 inputs (run route-20260912T161102Z-c40d)",
              "computed": 23.7247,
              "unit": "m/s"
            }
          ],
          "inferred": [
            "Start SoC 96 percent, 220 km, no optional loop, and two 20-minute swaps are carried from the 13:15 request because the 14:02 message changed only the end SoC.",
            "Array input is assumed zero."
          ],
          "resolution": "Run is feasible at 22 m/s under v2-1 with the 35 percent end SoC. Juno should still confirm v2-1 so the posted margin is the one the team plans against.",
          "checker_run": {
            "checker": "route",
            "version": "1",
            "run_id": "route-20260912T161102Z-51cc"
          }
        }
      }
    ]
  },
  {
    "id": "rc1-clean",
    "title": "RC1 · clean control",
    "channel": "#ks4-electrical",
    "channel_id": "C00SYN01",
    "fixture": "rc1-clean.json",
    "kind": "control",
    "summary": "Text, diagram and printed value agree. The reviewer posts a clean card and nothing else.",
    "events": [
      {
        "event_id": "ev-1787062320000100-0001",
        "at": "2026-08-19T18:40:02Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "message_read",
        "ts": "1787062320.000100",
        "from": "Dara Voss",
        "is_bot": false,
        "text": "Precharge board r2 review doc is up. Dropped one film cap, bus is now 680 uF.",
        "is_change": true
      },
      {
        "event_id": "ev-1787062320000100-0002",
        "at": "2026-08-19T18:40:04Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "message_read",
        "ts": "1787064000.000500",
        "from": "Tam Holloway",
        "is_bot": false,
        "text": "Relay close timer in firmware is 2.5 s, matches the doc.",
        "is_change": false
      },
      {
        "event_id": "ev-1787062320000100-0003",
        "at": "2026-08-19T18:40:06Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "message_read",
        "ts": "1787166300.000600",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer can you check section 3 of the r2 doc before I sign the review?",
        "is_change": false
      },
      {
        "event_id": "ev-1787062320000100-0004",
        "at": "2026-08-19T18:40:08Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "document_read",
        "document": "precharge-review-r2-clean.docx",
        "revision": "r2",
        "sha256": "f4baeedfb68c3d448b4a6a9ff47da3b7ec0491899e206a0945a6b58fd65d43c2",
        "line_count": 12,
        "named_in_ts": "1787062320.000100"
      },
      {
        "event_id": "ev-1787062320000100-0005",
        "at": "2026-08-19T18:40:10Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "check_run",
        "run_id": "rc-20260912T151500Z-0c9e",
        "checker": "rc",
        "version": "1",
        "inputs": {
          "R_ohm": 470,
          "threshold": 0.999,
          "timer_s": 2.5,
          "capacitances": [
            {
              "label": "680uF_text",
              "C_F": 0.00068
            },
            {
              "label": "750uF_diagram",
              "C_F": 0.00075
            },
            {
              "label": "820uF_change",
              "C_F": 0.00082
            },
            {
              "label": "2mF_example",
              "C_F": 0.002
            }
          ],
          "printed": [
            {
              "label": "printed_2.435",
              "value_s": 2.435,
              "against": [
                "680uF_text",
                "750uF_diagram"
              ]
            },
            {
              "label": "printed_6.91",
              "value_s": 6.91,
              "against": [
                "2mF_example"
              ]
            }
          ],
          "tolerance_s": 0.0005
        },
        "outputs": {
          "t_99.9 at 680 uF": {
            "computed": 2.2077,
            "unit": "s",
            "printed": 2.208
          },
          "t_99.9 at 2 mF": {
            "computed": 6.4933,
            "unit": "s",
            "printed": 6.49
          }
        },
        "checks": [
          {
            "name": "t_99.9 at 680 uF",
            "pass": true,
            "expected": 2.208,
            "actual": 2.2077
          },
          {
            "name": "t_99.9 at 2 mF",
            "pass": true,
            "expected": 6.49,
            "actual": 6.4933
          }
        ],
        "error": null,
        "evidence_refs": [
          {
            "kind": "document",
            "id": "1111111111111111111111111111111111111111111111111111111111111111"
          }
        ]
      },
      {
        "event_id": "ev-1787062320000100-0006",
        "at": "2026-08-19T18:40:12Z",
        "thread": "1787062320.000100",
        "trigger_ts": "1787166300.000600",
        "kind": "finding_published",
        "finding": {
          "finding_id": "fnd-rc1-001",
          "status": "live",
          "requirements_revision": "1787062320.000100",
          "discrepancy": "none",
          "why_it_matters": "All three printed results reproduce within 0.5 ms. Relay close at 2.5 s leaves 292 ms margin at 680 uF.",
          "sources": [
            {
              "kind": "document",
              "id": "precharge-review-r2-clean.docx",
              "revision": "r2",
              "sha256": "1111111111111111111111111111111111111111111111111111111111111111",
              "locator": "sections 2 to 4"
            }
          ],
          "reproduced": [
            {
              "label": "t_99.9 at 680 uF",
              "computed": 2.2077,
              "unit": "s",
              "printed": 2.208,
              "matches": true,
              "tolerance": 0.0005
            },
            {
              "label": "t_99.9 at 2 mF",
              "computed": 6.4933,
              "unit": "s",
              "printed": 6.49,
              "matches": true,
              "tolerance": 0.005
            }
          ],
          "inferred": [],
          "resolution": "No action. Review can be signed against r2.",
          "checker_run": {
            "checker": "rc",
            "version": "1",
            "run_id": "rc-20260912T151500Z-0c9e"
          }
        }
      }
    ]
  },
  {
    "id": "rc2-conflict",
    "title": "RC2 · conflicting evidence",
    "channel": "#ks4-strategy-sim",
    "channel_id": "C00SYN02",
    "fixture": "rc2-conflict.json",
    "kind": "control",
    "summary": "Two candidate masses (318 and 310 kg). The reviewer computes both and asks Milo instead of choosing.",
    "events": [
      {
        "event_id": "ev-1786472100000800-0001",
        "at": "2026-08-11T17:20:02Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1783092000.000700",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Sim inputs v2-0 posted for the summer runs.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0002",
        "at": "2026-08-11T17:20:04Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1784929680.000300",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Found why last week's numbers looked optimistic: we were still on KS-3 mass and Crr.\nv2-1 has the post-suspension values (318 kg, Crr 0.0048). Use v2-1 for anything after today.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0003",
        "at": "2026-08-11T17:20:06Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1784930520.000400",
        "from": "Ines Calder",
        "is_bot": false,
        "text": "Confirmed, corner weights from Tuesday add up to 318 with driver.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0004",
        "at": "2026-08-11T17:20:08Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1785427200.001000",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "v2-1 mass may be 8 kg high, the ballast was on the scale. Re-weigh pending.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0005",
        "at": "2026-08-11T17:20:10Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1786472100.000800",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer run the Northgate to Ferris segment (220 km, no optional loop), start SoC 96%, end SoC 40%, two 20-minute driver swaps, 22 m/s constant. I grabbed the params from the July 3 sheet.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0006",
        "at": "2026-08-11T17:20:12Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-0.xlsx",
        "revision": "v2-0",
        "sha256": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f",
        "line_count": 9,
        "named_in_ts": "1783092000.000700"
      },
      {
        "event_id": "ev-1786472100000800-0007",
        "at": "2026-08-11T17:20:14Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-1.xlsx",
        "revision": "v2-1",
        "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
        "line_count": 10,
        "named_in_ts": "1784929680.000300"
      },
      {
        "event_id": "ev-1786472100000800-0008",
        "at": "2026-08-11T17:20:16Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "check_run",
        "checker": "route",
        "version": "1",
        "inputs": {
          "mass_kg": 318,
          "Crr": 0.0048,
          "CdA": 0.12,
          "rho": 1.2,
          "v_mps": 22,
          "d_m": 220000,
          "pack_kWh": 5.2,
          "soc_start": 0.96,
          "soc_end": 0.4,
          "alternative_mass_kg": [
            310
          ]
        },
        "outputs": {
          "budget_kWh": 2.912,
          "primary": "mass_318kg",
          "cases": {
            "mass_318kg": {
              "mass_kg": 318.0,
              "rolling_N": 14.974,
              "aero_N": 34.848,
              "total_N": 49.822,
              "energy_kWh": 3.0447,
              "budget_kWh": 2.912,
              "feasible": false,
              "v_max_mps": 21.3037
            },
            "mass_310kg": {
              "mass_kg": 310.0,
              "rolling_N": 14.5973,
              "aero_N": 34.848,
              "total_N": 49.4453,
              "energy_kWh": 3.0217,
              "budget_kWh": 2.912,
              "feasible": false,
              "v_max_mps": 21.4261
            }
          }
        },
        "checks": [
          {
            "name": "mass_318kg_feasible",
            "pass": false,
            "expected": 2.912,
            "actual": 3.0447
          },
          {
            "name": "mass_310kg_feasible",
            "pass": false,
            "expected": 2.912,
            "actual": 3.0217
          }
        ],
        "error": null,
        "run_id": "route-20260912T161056Z-d049",
        "evidence_refs": [
          {
            "kind": "message",
            "id": "1786472100.000800"
          },
          {
            "kind": "message",
            "id": "1784929680.000300"
          },
          {
            "kind": "message",
            "id": "1784930520.000400"
          },
          {
            "kind": "message",
            "id": "1785427200.001000"
          },
          {
            "kind": "document",
            "id": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4"
          }
        ]
      },
      {
        "event_id": "ev-1786472100000800-0009",
        "at": "2026-08-11T17:20:18Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "finding_published",
        "finding": {
          "finding_id": "fnd-rc2-001",
          "status": "live",
          "requirements_revision": "1786472100.000800",
          "discrepancy": "The request uses the July 3 sheet (v2-0). v2-1 (July 24) is the latest named inputs, but Milo's July 30 message says the v2-1 mass may be 8 kg high because ballast was on the scale, with a re-weigh pending. No re-weigh has been posted. With the 96 to 40 percent budget of 2.912 kWh, 22 m/s is not feasible at either 318 kg (3.045 kWh) or 310 kg (3.022 kWh). The mass question does not change the feasibility answer for this request, but it does change the margin and the max speed, and it is unresolved.",
          "why_it_matters": "Either mass gives a shortfall of at least 0.11 kWh at 22 m/s. Which mass is right decides whether the max constant speed is 21.30 or 21.43 m/s. The reviewer cannot pick one; only a re-weigh can.",
          "sources": [
            {
              "kind": "message",
              "id": "1786472100.000800",
              "quote": "I grabbed the params from the July 3 sheet."
            },
            {
              "kind": "message",
              "id": "1784929680.000300",
              "quote": "v2-1 has the post-suspension values (318 kg, Crr 0.0048). Use v2-1 for anything after today."
            },
            {
              "kind": "message",
              "id": "1784930520.000400",
              "quote": "Confirmed, corner weights from Tuesday add up to 318 with driver."
            },
            {
              "kind": "message",
              "id": "1785427200.001000",
              "quote": "v2-1 mass may be 8 kg high, the ballast was on the scale. Re-weigh pending."
            },
            {
              "kind": "document",
              "id": "ks4-sim-inputs-v2-1.xlsx",
              "revision": "v2-1",
              "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
              "locator": "sheet params, rows 2 to 5",
              "quote": "mass_kg 318, Crr 0.0048, CdA 0.12, pack_kWh 5.2"
            }
          ],
          "reproduced": [
            {
              "label": "budget, SoC 96 to 40 percent",
              "computed": 2.912,
              "unit": "kWh"
            },
            {
              "label": "energy at 22 m/s, 318 kg, Crr 0.0048",
              "computed": 3.0447,
              "unit": "kWh"
            },
            {
              "label": "energy at 22 m/s, 310 kg, Crr 0.0048",
              "computed": 3.0217,
              "unit": "kWh"
            },
            {
              "label": "max feasible speed, 318 kg",
              "computed": 21.3037,
              "unit": "m/s"
            },
            {
              "label": "max feasible speed, 310 kg",
              "computed": 21.4261,
              "unit": "m/s"
            }
          ],
          "inferred": [
            "310 kg is Milo's stated 8 kg correction applied to 318 kg. It is a candidate, not a measured value.",
            "Crr 0.0048 is carried unchanged for both masses because the July 30 message questions only the mass.",
            "Array input is assumed zero. Optional loop excluded and two 20-minute swaps taken from the request text."
          ],
          "resolution": "Milo posts the re-weigh result, or states that 318 kg stands. Until then neither mass is final and the run is blocked on that answer.",
          "question": {
            "to": "Milo Trent",
            "ask": "Has the re-weigh from your July 30 message happened? Is the KS-4 mass with driver 318 kg or 310 kg?"
          },
          "checker_run": {
            "checker": "route",
            "version": "1",
            "run_id": "route-20260912T161056Z-d049"
          }
        }
      }
    ]
  },
  {
    "id": "rc3-midrun",
    "title": "RC3 · mid-run revision",
    "channel": "#ks4-strategy-sim",
    "channel_id": "C00SYN02",
    "fixture": "rc3-midrun.json",
    "kind": "control",
    "summary": "Milo's change lands while the check runs. publish_result refuses the stale run; a new run publishes against the new revision.",
    "events": [
      {
        "event_id": "ev-1786472100000800-0001",
        "at": "2026-08-11T18:00:02Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1783092000.000700",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Sim inputs v2-0 posted for the summer runs.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0002",
        "at": "2026-08-11T18:00:04Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1784929680.000300",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Found why last week's numbers looked optimistic: we were still on KS-3 mass and Crr.\nv2-1 has the post-suspension values (318 kg, Crr 0.0048). Use v2-1 for anything after today.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0003",
        "at": "2026-08-11T18:00:06Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1784930520.000400",
        "from": "Ines Calder",
        "is_bot": false,
        "text": "Confirmed, corner weights from Tuesday add up to 318 with driver.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0004",
        "at": "2026-08-11T18:00:08Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1786472100.000800",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer run the Northgate to Ferris segment (220 km, no optional loop), start SoC 96%, end SoC 40%, two 20-minute driver swaps, 22 m/s constant. I grabbed the params from the July 3 sheet.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0005",
        "at": "2026-08-11T18:00:10Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-0.xlsx",
        "revision": "v2-0",
        "sha256": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f",
        "line_count": 9,
        "named_in_ts": "1783092000.000700"
      },
      {
        "event_id": "ev-1786472100000800-0006",
        "at": "2026-08-11T18:00:12Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-1.xlsx",
        "revision": "v2-1",
        "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
        "line_count": 10,
        "named_in_ts": "1784929680.000300"
      },
      {
        "event_id": "ev-1786472100000800-0007",
        "at": "2026-08-11T18:00:14Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "check_run",
        "run_id": "route-20260912T161102Z-de45",
        "checker": "route",
        "version": "1",
        "inputs": {
          "v2-0": {
            "mass_kg": 290,
            "Crr": 0.004,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.4
          },
          "v2-1": {
            "mass_kg": 318,
            "Crr": 0.0048,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.4
          }
        },
        "outputs": {
          "budget, SoC 96 to 40 percent": {
            "computed": 2.912,
            "unit": "kWh"
          },
          "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-0665)": {
            "computed": 2.825,
            "unit": "kWh"
          },
          "energy at 22 m/s, v2-1 inputs": {
            "computed": 3.0447,
            "unit": "kWh"
          },
          "max feasible speed, v2-0 inputs (run route-20260912T161102Z-0665)": {
            "computed": 22.4448,
            "unit": "m/s"
          },
          "max feasible speed, v2-1 inputs": {
            "computed": 21.3037,
            "unit": "m/s"
          }
        },
        "checks": [
          {
            "name": "budget, SoC 96 to 40 percent",
            "pass": true,
            "actual": 2.912
          },
          {
            "name": "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-0665)",
            "pass": true,
            "actual": 2.825
          },
          {
            "name": "energy at 22 m/s, v2-1 inputs",
            "pass": true,
            "actual": 3.0447
          },
          {
            "name": "max feasible speed, v2-0 inputs (run route-20260912T161102Z-0665)",
            "pass": true,
            "actual": 22.4448
          },
          {
            "name": "max feasible speed, v2-1 inputs",
            "pass": true,
            "actual": 21.3037
          }
        ],
        "error": null,
        "evidence_refs": [
          {
            "kind": "message",
            "id": "1786472100.000800"
          },
          {
            "kind": "message",
            "id": "1784929680.000300"
          },
          {
            "kind": "message",
            "id": "1784930520.000400"
          },
          {
            "kind": "document",
            "id": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f"
          },
          {
            "kind": "document",
            "id": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4"
          }
        ]
      },
      {
        "event_id": "ev-1786472100000800-0008",
        "at": "2026-08-11T18:00:16Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "message_read",
        "ts": "1786474920.000900",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Race director allows end SoC 35% for this segment now, not 40%.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0009",
        "at": "2026-08-11T18:00:18Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786472100.000800",
        "kind": "publish_refused",
        "run_id": "route-20260912T161102Z-de45",
        "bound_revision": "1786472100.000800",
        "current_revision": "1786474920.000900",
        "reason": "thread revision moved from the trigger to Milo's 35 percent message while the check ran"
      },
      {
        "event_id": "ev-1786472100000800-0010",
        "at": "2026-08-11T18:00:20Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1783092000.000700",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Sim inputs v2-0 posted for the summer runs.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0011",
        "at": "2026-08-11T18:00:22Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1784929680.000300",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Found why last week's numbers looked optimistic: we were still on KS-3 mass and Crr.\nv2-1 has the post-suspension values (318 kg, Crr 0.0048). Use v2-1 for anything after today.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0012",
        "at": "2026-08-11T18:00:24Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1784930520.000400",
        "from": "Ines Calder",
        "is_bot": false,
        "text": "Confirmed, corner weights from Tuesday add up to 318 with driver.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0013",
        "at": "2026-08-11T18:00:26Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1786472100.000800",
        "from": "Juno Marsh",
        "is_bot": false,
        "text": "@reviewer run the Northgate to Ferris segment (220 km, no optional loop), start SoC 96%, end SoC 40%, two 20-minute driver swaps, 22 m/s constant. I grabbed the params from the July 3 sheet.",
        "is_change": false
      },
      {
        "event_id": "ev-1786472100000800-0014",
        "at": "2026-08-11T18:00:28Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "message_read",
        "ts": "1786474920.000900",
        "from": "Milo Trent",
        "is_bot": false,
        "text": "Race director allows end SoC 35% for this segment now, not 40%.",
        "is_change": true
      },
      {
        "event_id": "ev-1786472100000800-0015",
        "at": "2026-08-11T18:00:30Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-0.xlsx",
        "revision": "v2-0",
        "sha256": "90b83e645932f0b9a8cc447d3ce86ac30398948d702474016a7e172723cb230f",
        "line_count": 9,
        "named_in_ts": "1783092000.000700"
      },
      {
        "event_id": "ev-1786472100000800-0016",
        "at": "2026-08-11T18:00:32Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "document_read",
        "document": "ks4-sim-inputs-v2-1.xlsx",
        "revision": "v2-1",
        "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
        "line_count": 10,
        "named_in_ts": "1784929680.000300"
      },
      {
        "event_id": "ev-1786472100000800-0017",
        "at": "2026-08-11T18:00:34Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "check_run",
        "run_id": "route-20260912T161102Z-51cc",
        "checker": "route",
        "version": "1",
        "inputs": {
          "v2-0": {
            "mass_kg": 290,
            "Crr": 0.004,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.35
          },
          "v2-1": {
            "mass_kg": 318,
            "Crr": 0.0048,
            "CdA": 0.12,
            "rho": 1.2,
            "v_mps": 22,
            "d_m": 220000,
            "pack_kWh": 5.2,
            "soc_start": 0.96,
            "soc_end": 0.35
          }
        },
        "outputs": {
          "budget, SoC 96 to 35 percent": {
            "computed": 3.172,
            "unit": "kWh"
          },
          "energy at 22 m/s, v2-1 inputs": {
            "computed": 3.0447,
            "unit": "kWh"
          },
          "max feasible speed, v2-1 inputs": {
            "computed": 22.6481,
            "unit": "m/s"
          },
          "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-c40d)": {
            "computed": 2.825,
            "unit": "kWh"
          },
          "max feasible speed, v2-0 inputs (run route-20260912T161102Z-c40d)": {
            "computed": 23.7247,
            "unit": "m/s"
          }
        },
        "checks": [
          {
            "name": "budget, SoC 96 to 35 percent",
            "pass": true,
            "actual": 3.172
          },
          {
            "name": "energy at 22 m/s, v2-1 inputs",
            "pass": true,
            "actual": 3.0447
          },
          {
            "name": "max feasible speed, v2-1 inputs",
            "pass": true,
            "actual": 22.6481
          },
          {
            "name": "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-c40d)",
            "pass": true,
            "actual": 2.825
          },
          {
            "name": "max feasible speed, v2-0 inputs (run route-20260912T161102Z-c40d)",
            "pass": true,
            "actual": 23.7247
          }
        ],
        "error": null,
        "evidence_refs": [
          {
            "kind": "message",
            "id": "1786474920.000900"
          },
          {
            "kind": "message",
            "id": "1786472100.000800"
          },
          {
            "kind": "message",
            "id": "1784929680.000300"
          },
          {
            "kind": "document",
            "id": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4"
          }
        ]
      },
      {
        "event_id": "ev-1786472100000800-0018",
        "at": "2026-08-11T18:00:36Z",
        "thread": "1786472100.000800",
        "trigger_ts": "1786474920.000900",
        "kind": "finding_published",
        "finding": {
          "finding_id": "fnd-b-35-002",
          "status": "live",
          "supersedes": "fnd-b-40-001",
          "requirements_revision": "1786474920.000900",
          "discrepancy": "With end SoC 35 percent the budget is 3.172 kWh. At 22 m/s over 220 km, v2-1 gives 3.045 kWh and v2-0 gives 2.825 kWh, so the segment is feasible under both input files and the conclusion no longer flips. The request still names the July 3 sheet; v2-1 remains the inputs Milo named for anything after July 24.",
          "why_it_matters": "The 40 percent card said 22 m/s did not fit under v2-1. That is no longer true at 35 percent, with 0.127 kWh of margin. The max constant speed under v2-1 rises from 21.30 to 22.65 m/s. The input-version choice still changes the margin by 0.22 kWh, so the run stays bound to v2-1.",
          "sources": [
            {
              "kind": "message",
              "id": "1786474920.000900",
              "quote": "Race director allows end SoC 35% for this segment now, not 40%."
            },
            {
              "kind": "message",
              "id": "1786472100.000800",
              "quote": "Northgate to Ferris segment (220 km, no optional loop), start SoC 96%"
            },
            {
              "kind": "message",
              "id": "1784929680.000300",
              "quote": "Use v2-1 for anything after today."
            },
            {
              "kind": "document",
              "id": "ks4-sim-inputs-v2-1.xlsx",
              "revision": "v2-1",
              "sha256": "8e2419c7620047d5b80fa273828bd062fecbe50bd3404aed39dd2301d07e6ab4",
              "locator": "sheet params, rows 2 to 5",
              "quote": "mass_kg 318, Crr 0.0048, CdA 0.12, pack_kWh 5.2"
            }
          ],
          "reproduced": [
            {
              "label": "budget, SoC 96 to 35 percent",
              "computed": 3.172,
              "unit": "kWh"
            },
            {
              "label": "energy at 22 m/s, v2-1 inputs",
              "computed": 3.0447,
              "unit": "kWh"
            },
            {
              "label": "max feasible speed, v2-1 inputs",
              "computed": 22.6481,
              "unit": "m/s"
            },
            {
              "label": "energy at 22 m/s, v2-0 inputs (run route-20260912T161102Z-c40d)",
              "computed": 2.825,
              "unit": "kWh"
            },
            {
              "label": "max feasible speed, v2-0 inputs (run route-20260912T161102Z-c40d)",
              "computed": 23.7247,
              "unit": "m/s"
            }
          ],
          "inferred": [
            "Start SoC 96 percent, 220 km, no optional loop, and two 20-minute swaps are carried from the 13:15 request because the 14:02 message changed only the end SoC.",
            "Array input is assumed zero."
          ],
          "resolution": "Run is feasible at 22 m/s under v2-1 with the 35 percent end SoC. Juno should still confirm v2-1 so the posted margin is the one the team plans against.",
          "checker_run": {
            "checker": "route",
            "version": "1",
            "run_id": "route-20260912T161102Z-51cc"
          }
        }
      }
    ]
  }
];

export const DEFAULT_SCENARIO = SCENARIOS[0]!.id;
