/* GENERATED by apps/web/scripts/gen-workspace-synthetic.py — do not edit by hand.
 * Synthetic FRC-style engineering chatter that widens the Workspace page's
 * exact-match message index (apps/web/src/lib/workspace-index.ts) beyond the
 * ~39-message fixtures/workspace/kestrel-workspace.json seed. Merged into
 * WORKSPACE by build-demo-data.py; run gen-workspace-synthetic.py again to
 * regenerate this file, then re-run build-demo-data.py.
 */
import type { WorkspaceMessage } from "../workspace-index";

export const WORKSPACE_SYNTHETIC: WorkspaceMessage[] = [
  {
    "ts": "1772821480.203228",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Chassis weighed in at 14 kg on the shop scale, 43 kg under the estimate in the sim doc.",
    "files": []
  },
  {
    "ts": "1772824154.311936",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Ordered the TE-ratchet-06 for 807 USD, budget line still has 123.62 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1772964343.994058",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1772824154.311936",
    "text": "Confirmed, matches what I have: 740.4 ms.",
    "files": []
  },
  {
    "ts": "1772966769.183454",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1772964343.994058",
    "text": "Ran it again, got 865.6 V this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1773052231.421385",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1772821480.203228",
    "text": "That lines up with the CIM-2 datasheet.",
    "files": []
  },
  {
    "ts": "1773073295.647189",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Drivetrain draws 381 A steady state at 138.6 V under full load on the practice field. See drivetrain-current-budget-r3.pdf.",
    "files": [
      "drivetrain-current-budget-r3.pdf"
    ]
  },
  {
    "ts": "1773129526.702045",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1773073295.647189",
    "text": "Ran it again, got 562.0 s this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1773170560.296853",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Quote for the FLEX-24-6mm came back at 211.81 USD, 241 USD cheaper than the first vendor. See shock-travel-spec-r1.xlsx.",
    "files": [
      "shock-travel-spec-r1.xlsx"
    ]
  },
  {
    "ts": "1773220844.929129",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Reviewed AM-3927 torque spec: rated 197.1 N·m continuous, 711.55 N·m peak for 2 seconds.",
    "files": []
  },
  {
    "ts": "1773256425.160280",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "CAN bus utilization sitting around 843.42 percent at full tele-op load.",
    "files": []
  },
  {
    "ts": "1773309932.303232",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Scratch that — the 10AWG-red spec sheet says 854.91 V max, we were running it at 146 V.",
    "files": []
  },
  {
    "ts": "1773364041.432816",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "PDH main breaker is 872 A, sized for 550 A continuous draw from the drivetrain.",
    "files": []
  },
  {
    "ts": "1773365877.204419",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Bumper foam compresses 180.5 mm before the frame rail contacts, tested at 880 N preload.",
    "files": []
  },
  {
    "ts": "1773383093.614241",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": "1773052231.421385",
    "text": "Confirmed, matches what I have: 113.6 mm.",
    "files": []
  },
  {
    "ts": "1773399531.689374",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Quote for the REV-14B came back at 44.86 USD, 366.27 USD cheaper than the first vendor.",
    "files": []
  },
  {
    "ts": "1773429763.778538",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Chassis weighed in at 355 kg on the shop scale, 250.04 kg under the estimate in the sim doc. See arm-torque-review-r3.docx.",
    "files": [
      "arm-torque-review-r3.docx"
    ]
  },
  {
    "ts": "1773458478.282671",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1773364041.432816",
    "text": "Good catch — updating the doc to 331 mm.",
    "files": []
  },
  {
    "ts": "1773491429.239155",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Instead of the CIM-2 we're routing through a 266.8 A breaker, quote came back at 323 USD.",
    "files": []
  },
  {
    "ts": "1773581671.858861",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1773129526.702045",
    "text": "Confirmed, matches what I have: 83.2 s.",
    "files": []
  },
  {
    "ts": "1773591236.928063",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "CAN bus utilization sitting around 334 percent at full tele-op load.",
    "files": []
  },
  {
    "ts": "1773618510.944450",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Battery internal resistance reads 519.18 ohm on the new pack, 416.94 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1773640738.618678",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Ordered the PDH-rev2 for 303.8 USD, budget line still has 22 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1773676201.317033",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Now, not later — bus target moves to 317.2 V nominal, precharge resistor stays 385.4 ohm.",
    "files": []
  },
  {
    "ts": "1773692829.087653",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1772966769.183454",
    "text": "Pushed the fix, retest shows 59 ohm now.",
    "files": []
  },
  {
    "ts": "1773770091.824400",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Ordered the REV-14B for 400.5 USD, budget line still has 489.35 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1773780775.774440",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Precharge sequence takes 500.6 ms to settle, relay closes 582 ms after enable.",
    "files": []
  },
  {
    "ts": "1773841581.469670",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1772964343.994058",
    "text": "Pushed the fix, retest shows 428.4 kg now.",
    "files": []
  },
  {
    "ts": "1773862286.677172",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Field wiring run is 554.4 mm gauge core, 679 mm insulation OD, matches the harness doc. See arm-torque-review-r3.docx.",
    "files": [
      "arm-torque-review-r3.docx"
    ]
  },
  {
    "ts": "1773892719.911857",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1773676201.317033",
    "text": "Can we get 61 kg confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1774059316.314051",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1773073295.647189",
    "text": "Pushed the fix, retest shows 741 ms now.",
    "files": []
  },
  {
    "ts": "1774094176.382281",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Encoder counts per rev confirmed at 693, gear ratio still 538.52:1 same as last season.",
    "files": []
  },
  {
    "ts": "1774104642.740017",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1772966769.183454",
    "text": "Can we get 292 uF confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1774105585.542557",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Relay timer from enable to drive-ready is 682.49 ms, was 712.1 ms before the firmware bump.",
    "files": []
  },
  {
    "ts": "1774114077.799675",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Precharge sequence takes 3.47 ms to settle, relay closes 163.54 ms after enable.",
    "files": []
  },
  {
    "ts": "1774155378.255794",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Arm holding torque needs about 797 N·m at full extension, gearbox rated for 855 N·m.",
    "files": []
  },
  {
    "ts": "1774314605.795512",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Motor controller brownout threshold set to 148 V, current limit 879.2 A per module.",
    "files": []
  },
  {
    "ts": "1774327516.455961",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1773640738.618678",
    "text": "That lines up with the S3-relay-40A datasheet.",
    "files": []
  },
  {
    "ts": "1774460328.032692",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1773364041.432816",
    "text": "Ran it again, got 603.6 mm this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1774576983.461642",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1773256425.160280",
    "text": "Agreed, going with 383 V for the design review.",
    "files": []
  },
  {
    "ts": "1774628600.288849",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1773676201.317033",
    "text": "Pushed the fix, retest shows 585 s now.",
    "files": []
  },
  {
    "ts": "1774675868.344667",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Motor controller brownout threshold set to 38.9 V, current limit 167.5 A per module.",
    "files": []
  },
  {
    "ts": "1774700407.858957",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Reviewed CIM-2 torque spec: rated 184 N·m continuous, 282.21 N·m peak for 2 seconds.",
    "files": []
  },
  {
    "ts": "1774834057.189084",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Precharge sequence takes 136.0 ms to settle, relay closes 735.34 ms after enable.",
    "files": []
  },
  {
    "ts": "1774847521.390142",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Actually the shock travel spec is 373 mm, not 448.23 mm — measured it myself with calipers.",
    "files": []
  },
  {
    "ts": "1774993717.303619",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1772821480.203228",
    "text": "Confirmed, matches what I have: 302 USD.",
    "files": []
  },
  {
    "ts": "1775037065.681446",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Actually the shock travel spec is 653 mm, not 298 mm — measured it myself with calipers.",
    "files": []
  },
  {
    "ts": "1775108243.601169",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Actually the shock travel spec is 151.48 mm, not 444 mm — measured it myself with calipers.",
    "files": []
  },
  {
    "ts": "1775117407.324836",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": "1774059316.314051",
    "text": "That lines up with the CIM-2 datasheet.",
    "files": []
  },
  {
    "ts": "1775183503.144293",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Reviewed FLEX-24-6mm torque spec: rated 214.1 N·m continuous, 597.5 N·m peak for 2 seconds.",
    "files": []
  },
  {
    "ts": "1775199704.074102",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Ordered the WCP-1350 for 482.17 USD, budget line still has 204.3 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1775224324.410340",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1774155378.255794",
    "text": "Confirmed, matches what I have: 402.2 mm.",
    "files": []
  },
  {
    "ts": "1775333614.135963",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Field wiring run is 345 mm gauge core, 133.47 mm insulation OD, matches the harness doc.",
    "files": []
  },
  {
    "ts": "1775533094.765375",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Actually the shock travel spec is 820 mm, not 774.62 mm — measured it myself with calipers.",
    "files": []
  },
  {
    "ts": "1775586259.072045",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Relay timer from enable to drive-ready is 638.69 ms, was 487 ms before the firmware bump.",
    "files": []
  },
  {
    "ts": "1775597537.465319",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Scratch that — the WCP-1350 spec sheet says 554 V max, we were running it at 41.14 V.",
    "files": []
  },
  {
    "ts": "1775668613.406216",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Ambient in the electronics bay hit 516.3 deg C during the long auto test, fans kick on at 373 deg C.",
    "files": []
  },
  {
    "ts": "1775812581.227495",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1773383093.614241",
    "text": "Confirmed, matches what I have: 788.9 uF.",
    "files": []
  },
  {
    "ts": "1775843821.049200",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1775812581.227495",
    "text": "Good catch — updating the doc to 259 ms.",
    "files": []
  },
  {
    "ts": "1775869801.561071",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Precharge sequence takes 34 ms to settle, relay closes 423.4 ms after enable.",
    "files": []
  },
  {
    "ts": "1775915323.514317",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": "1773365877.204419",
    "text": "Attaching the updated numbers now.",
    "files": []
  },
  {
    "ts": "1775917798.328844",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Swapped in the FLEX-24-6mm, new draw is 520.0 A vs 674.09 A on the old part — logged in the test doc.",
    "files": []
  },
  {
    "ts": "1775927275.029620",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1773862286.677172",
    "text": "Confirmed, matches what I have: 703 A.",
    "files": []
  },
  {
    "ts": "1775934494.446410",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Correction: bus is now 457.0 uF after swapping the PDH-rev2, not 8.15 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1776082281.278436",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Chassis weighed in at 414.7 kg on the shop scale, 21.3 kg under the estimate in the sim doc.",
    "files": []
  },
  {
    "ts": "1776152837.305493",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Actually the shock travel spec is 294.54 mm, not 598.54 mm — measured it myself with calipers.",
    "files": []
  },
  {
    "ts": "1776189394.579488",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1776152837.305493",
    "text": "Can we get 37 uF confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1776197595.029976",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1773640738.618678",
    "text": "That lines up with the FLEX-24-6mm datasheet.",
    "files": []
  },
  {
    "ts": "1776220197.731697",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": "1774834057.189084",
    "text": "Ran it again, got 77 V this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1776233395.401620",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "\"354.5 A is fine for that motor,\" Dara said, so we're not derating below 75.9 A.",
    "files": []
  },
  {
    "ts": "1776411655.180547",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Battery internal resistance reads 244.6 ohm on the new pack, 444.55 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1776413595.424553",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Battery internal resistance reads 402.06 ohm on the new pack, 275 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1776477515.688524",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": "1776413595.424553",
    "text": "Can we get 70.4 s confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1776536855.569715",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Drivetrain draws 352.9 A steady state at 545.15 V under full load on the practice field.",
    "files": []
  },
  {
    "ts": "1776573366.689713",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Instead of the CIM-2 we're routing through a 120 A breaker, quote came back at 660.14 USD.",
    "files": []
  },
  {
    "ts": "1776916842.566221",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Correction: bus is now 373 uF after swapping the WCP-1350, not 834.2 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1777073665.399271",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Scratch that — the AM-3927 spec sheet says 444 V max, we were running it at 259.4 V. See bus-capacitance-memo-r2.pdf.",
    "files": [
      "bus-capacitance-memo-r2.pdf"
    ]
  },
  {
    "ts": "1777127933.692293",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1776916842.566221",
    "text": "Agreed, going with 17 ms for the design review. See pdh-breaker-sizing-r1.xlsx.",
    "files": [
      "pdh-breaker-sizing-r1.xlsx"
    ]
  },
  {
    "ts": "1777271115.029975",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Ambient in the electronics bay hit 640.78 deg C during the long auto test, fans kick on at 102.52 deg C.",
    "files": []
  },
  {
    "ts": "1777317364.283434",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "\"874.5 A is fine for that motor,\" Dara said, so we're not derating below 185 A.",
    "files": []
  },
  {
    "ts": "1777621160.320609",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Drivetrain draws 119.0 A steady state at 106 V under full load on the practice field.",
    "files": []
  },
  {
    "ts": "1777669942.852465",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1775224324.410340",
    "text": "Ran it again, got 15.2 USD this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1777692636.728832",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1774094176.382281",
    "text": "Good catch — updating the doc to 502 ms.",
    "files": []
  },
  {
    "ts": "1777797908.956748",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Instead of the AM-3927 we're routing through a 653 A breaker, quote came back at 697.49 USD.",
    "files": []
  },
  {
    "ts": "1777860914.897325",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": "1774576983.461642",
    "text": "Ran it again, got 636 mm this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1777912227.760360",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Bumper foam compresses 652.77 mm before the frame rail contacts, tested at 875 N preload.",
    "files": []
  },
  {
    "ts": "1777942273.930766",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1777317364.283434",
    "text": "Confirmed, matches what I have: 517 uF.",
    "files": []
  },
  {
    "ts": "1778003457.279767",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Now, not later — bus target moves to 778.91 V nominal, precharge resistor stays 700 ohm.",
    "files": []
  },
  {
    "ts": "1778278543.219215",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1773676201.317033",
    "text": "Agreed, going with 717.7 ms for the design review.",
    "files": []
  },
  {
    "ts": "1778389134.032911",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1775533094.765375",
    "text": "Agreed, going with 647.1 kg for the design review.",
    "files": []
  },
  {
    "ts": "1778484718.934866",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1775224324.410340",
    "text": "Agreed, going with 288.9 uF for the design review.",
    "files": []
  },
  {
    "ts": "1778566374.916614",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1773129526.702045",
    "text": "Can we get 776 USD confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1778604241.551463",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Now, not later — bus target moves to 755.95 V nominal, precharge resistor stays 649.4 ohm.",
    "files": []
  },
  {
    "ts": "1778681936.556943",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Updated: precharge resistor is now 485 ohm, supersedes the 176.2 ohm value from kickoff.",
    "files": []
  },
  {
    "ts": "1778729114.862973",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": "1774675868.344667",
    "text": "Confirmed, matches what I have: 754 A.",
    "files": []
  },
  {
    "ts": "1778788982.253157",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Actually the shock travel spec is 397.6 mm, not 544.5 mm — measured it myself with calipers.",
    "files": []
  },
  {
    "ts": "1778867666.290543",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Swapped in the REDLINE-775, new draw is 414 A vs 663.86 A on the old part — logged in the test doc.",
    "files": []
  },
  {
    "ts": "1779338083.656664",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Battery internal resistance reads 200 ohm on the new pack, 532.8 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1779371619.807804",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": "1778788982.253157",
    "text": "Ran it again, got 402.3 mm this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1779460293.420056",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Now, not later — bus target moves to 350.1 V nominal, precharge resistor stays 14 ohm.",
    "files": []
  },
  {
    "ts": "1779560181.448725",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Motor controller brownout threshold set to 623 V, current limit 615.33 A per module.",
    "files": []
  },
  {
    "ts": "1779566605.881500",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Arm holding torque needs about 127.7 N·m at full extension, gearbox rated for 293.5 N·m.",
    "files": []
  },
  {
    "ts": "1779696151.624943",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Bus capacitance measured at 227 uF across the FLEX-24-6mm, precharge resistor 232.86 ohm.",
    "files": []
  },
  {
    "ts": "1779714372.782751",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1777797908.956748",
    "text": "Attaching the updated numbers now.",
    "files": []
  },
  {
    "ts": "1779830557.898307",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "PDH main breaker is 548 A, sized for 104.51 A continuous draw from the drivetrain.",
    "files": []
  },
  {
    "ts": "1779860047.414192",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Correction: bus is now 170 uF after swapping the AM-3927, not 297.06 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1779901313.359906",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Field wiring run is 186 mm gauge core, 594.6 mm insulation OD, matches the harness doc.",
    "files": []
  },
  {
    "ts": "1779910328.915168",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1774628600.288849",
    "text": "That lines up with the REDLINE-775 datasheet.",
    "files": []
  },
  {
    "ts": "1780045712.166309",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": "1778484718.934866",
    "text": "Ran it again, got 562.5 USD this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1780074429.420884",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Bumper foam compresses 469.0 mm before the frame rail contacts, tested at 529.8 N preload.",
    "files": []
  },
  {
    "ts": "1780197310.739077",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Quote for the 10AWG-red came back at 266.3 USD, 375.4 USD cheaper than the first vendor.",
    "files": []
  },
  {
    "ts": "1780275096.414553",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1774114077.799675",
    "text": "Confirmed, matches what I have: 663.5 ohm.",
    "files": []
  },
  {
    "ts": "1780280951.661959",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": "1775117407.324836",
    "text": "That lines up with the FLEX-24-6mm datasheet.",
    "files": []
  },
  {
    "ts": "1780290992.559371",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1778484718.934866",
    "text": "Good catch — updating the doc to 756 kg.",
    "files": []
  },
  {
    "ts": "1780353560.701240",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "\"444.43 A is fine for that motor,\" Dara said, so we're not derating below 360.76 A.",
    "files": []
  },
  {
    "ts": "1780474841.660512",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "CAN bus utilization sitting around 157.4 percent at full tele-op load.",
    "files": []
  },
  {
    "ts": "1780495989.810688",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Ordered the TE-ratchet-06 for 40.17 USD, budget line still has 195 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1780592280.933136",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1773692829.087653",
    "text": "Ran it again, got 835.9 USD this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1780671229.909126",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1774059316.314051",
    "text": "Confirmed, matches what I have: 588 s. See pdh-breaker-sizing-r3.docx.",
    "files": [
      "pdh-breaker-sizing-r3.docx"
    ]
  },
  {
    "ts": "1780730068.676179",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Instead of the PDH-rev2 we're routing through a 321.53 A breaker, quote came back at 628.6 USD.",
    "files": []
  },
  {
    "ts": "1780734921.838321",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "\"640.95 A is fine for that motor,\" Dara said, so we're not derating below 401.7 A. See pdh-breaker-sizing-r2.docx.",
    "files": [
      "pdh-breaker-sizing-r2.docx"
    ]
  },
  {
    "ts": "1780752447.067805",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Now, not later — bus target moves to 817.7 V nominal, precharge resistor stays 12 ohm.",
    "files": []
  },
  {
    "ts": "1780797060.984301",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "\"125.4 A is fine for that motor,\" Dara said, so we're not derating below 861.62 A.",
    "files": []
  },
  {
    "ts": "1780875174.779284",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Bumper foam compresses 192.06 mm before the frame rail contacts, tested at 46.3 N preload.",
    "files": []
  },
  {
    "ts": "1781156956.887492",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Updated: precharge resistor is now 171.6 ohm, supersedes the 706.42 ohm value from kickoff.",
    "files": []
  },
  {
    "ts": "1781158872.285448",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Bumper foam compresses 380.8 mm before the frame rail contacts, tested at 634.47 N preload.",
    "files": []
  },
  {
    "ts": "1781219188.626337",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Actually the shock travel spec is 869.0 mm, not 177 mm — measured it myself with calipers.",
    "files": []
  },
  {
    "ts": "1781270354.403355",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Correction: bus is now 180.59 uF after swapping the S3-relay-40A, not 551.8 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1781329933.234122",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Updated: precharge resistor is now 598.38 ohm, supersedes the 846.7 ohm value from kickoff.",
    "files": []
  },
  {
    "ts": "1781715445.886612",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "CAN bus utilization sitting around 608 percent at full tele-op load.",
    "files": []
  },
  {
    "ts": "1781778956.180829",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Instead of the PDH-rev2 we're routing through a 668.78 A breaker, quote came back at 322.6 USD.",
    "files": []
  },
  {
    "ts": "1781781906.195213",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": "1780752447.067805",
    "text": "Confirmed, matches what I have: 150 ms.",
    "files": []
  },
  {
    "ts": "1781782604.989178",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Correction: bus is now 723.5 uF after swapping the AM-3927, not 127.91 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1781788254.679515",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "\"701 A is fine for that motor,\" Dara said, so we're not derating below 673 A. See shock-travel-spec-final.pdf.",
    "files": [
      "shock-travel-spec-final.pdf"
    ]
  },
  {
    "ts": "1781933439.083628",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": "1775183503.144293",
    "text": "Pushed the fix, retest shows 890.3 ms now.",
    "files": []
  },
  {
    "ts": "1781941432.046537",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": "1780353560.701240",
    "text": "Ran it again, got 243 USD this time, closer to spec. See purchasing-quote-final.docx.",
    "files": [
      "purchasing-quote-final.docx"
    ]
  },
  {
    "ts": "1781984627.086343",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Arm holding torque needs about 755 N·m at full extension, gearbox rated for 275 N·m. See pdh-breaker-sizing-r2.docx.",
    "files": [
      "pdh-breaker-sizing-r2.docx"
    ]
  },
  {
    "ts": "1782092860.785281",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Battery internal resistance reads 772 ohm on the new pack, 1.12 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1782109935.386986",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Correction: bus is now 505.4 uF after swapping the REDLINE-775, not 23.15 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1782257731.587085",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": "1778484718.934866",
    "text": "Agreed, going with 667.7 ohm for the design review.",
    "files": []
  },
  {
    "ts": "1782288408.836297",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Correction: bus is now 118 uF after swapping the S3-relay-40A, not 761.0 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1782303769.607292",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": "1777860914.897325",
    "text": "Agreed, going with 185.6 ohm for the design review.",
    "files": []
  },
  {
    "ts": "1782359809.350964",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Bus capacitance measured at 55.7 uF across the 10AWG-red, precharge resistor 20.6 ohm. See can-bus-utilization-r3.pdf.",
    "files": [
      "can-bus-utilization-r3.pdf"
    ]
  },
  {
    "ts": "1782371142.960087",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Quote for the 10AWG-red came back at 68.9 USD, 282.94 USD cheaper than the first vendor.",
    "files": []
  },
  {
    "ts": "1782661182.872452",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": "1773640738.618678",
    "text": "Confirmed, matches what I have: 169.7 uF.",
    "files": []
  },
  {
    "ts": "1782752602.268204",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": "1779910328.915168",
    "text": "Good catch — updating the doc to 429.0 ms.",
    "files": []
  },
  {
    "ts": "1782761301.043140",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Correction: bus is now 546 uF after swapping the REV-14B, not 709.84 uF like I said Tuesday.",
    "files": []
  },
  {
    "ts": "1782835011.724489",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "\"598.34 A is fine for that motor,\" Dara said, so we're not derating below 826.87 A.",
    "files": []
  },
  {
    "ts": "1782858089.954731",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Chassis weighed in at 140.1 kg on the shop scale, 210 kg under the estimate in the sim doc.",
    "files": []
  },
  {
    "ts": "1782915390.626565",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "CAN bus utilization sitting around 522.6 percent at full tele-op load.",
    "files": []
  },
  {
    "ts": "1783203868.096522",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Encoder counts per rev confirmed at 603, gear ratio still 878:1 same as last season.",
    "files": []
  },
  {
    "ts": "1783234630.836916",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Reviewed PDH-rev2 torque spec: rated 842.47 N·m continuous, 267.9 N·m peak for 2 seconds.",
    "files": []
  },
  {
    "ts": "1783288001.857138",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1775224324.410340",
    "text": "Can we get 668.6 uF confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1783363796.883625",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Ordered the REDLINE-775 for 354 USD, budget line still has 46.8 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1783413426.520856",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "PDH main breaker is 479.24 A, sized for 881.9 A continuous draw from the drivetrain.",
    "files": []
  },
  {
    "ts": "1783479272.870617",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Reviewed WCP-1350 torque spec: rated 45 N·m continuous, 703 N·m peak for 2 seconds.",
    "files": []
  },
  {
    "ts": "1783520476.387001",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": "1773862286.677172",
    "text": "Pushed the fix, retest shows 228.3 A now.",
    "files": []
  },
  {
    "ts": "1783604535.829832",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1777860914.897325",
    "text": "Agreed, going with 241.9 V for the design review.",
    "files": []
  },
  {
    "ts": "1783624513.692787",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Ambient in the electronics bay hit 820.2 deg C during the long auto test, fans kick on at 651.7 deg C. See pdh-breaker-sizing-r2.xlsx.",
    "files": [
      "pdh-breaker-sizing-r2.xlsx"
    ]
  },
  {
    "ts": "1783649195.422594",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Encoder counts per rev confirmed at 469.9, gear ratio still 78.36:1 same as last season.",
    "files": []
  },
  {
    "ts": "1783703249.128281",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": "1776152837.305493",
    "text": "Confirmed, matches what I have: 773 kg.",
    "files": []
  },
  {
    "ts": "1783734600.708595",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Instead of the WCP-1350 we're routing through a 307 A breaker, quote came back at 145 USD.",
    "files": []
  },
  {
    "ts": "1783790409.586780",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Relay timer from enable to drive-ready is 404.7 ms, was 39 ms before the firmware bump.",
    "files": []
  },
  {
    "ts": "1783902566.822137",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Ordered the REDLINE-775 for 423.7 USD, budget line still has 840.1 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1783902727.673319",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Encoder counts per rev confirmed at 631, gear ratio still 836.5:1 same as last season.",
    "files": []
  },
  {
    "ts": "1783918398.531833",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1781156956.887492",
    "text": "Pushed the fix, retest shows 542.3 s now.",
    "files": []
  },
  {
    "ts": "1783936929.550339",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Battery internal resistance reads 445 ohm on the new pack, 886.1 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1783982426.225145",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Battery internal resistance reads 270.1 ohm on the new pack, 460.09 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1783996585.446723",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Field wiring run is 534 mm gauge core, 245.2 mm insulation OD, matches the harness doc.",
    "files": []
  },
  {
    "ts": "1784035495.053179",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1782761301.043140",
    "text": "Can we get 291 uF confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1784078965.070310",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1779910328.915168",
    "text": "Confirmed, matches what I have: 255.6 s.",
    "files": []
  },
  {
    "ts": "1784152116.661363",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Field wiring run is 716.3 mm gauge core, 100.43 mm insulation OD, matches the harness doc. See purchasing-quote-r3.docx.",
    "files": [
      "purchasing-quote-r3.docx"
    ]
  },
  {
    "ts": "1784352209.020406",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": "1780671229.909126",
    "text": "Pushed the fix, retest shows 57 mm now.",
    "files": []
  },
  {
    "ts": "1784383553.377221",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Updated: precharge resistor is now 115.88 ohm, supersedes the 569.4 ohm value from kickoff.",
    "files": []
  },
  {
    "ts": "1784403008.303904",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": "1783790409.586780",
    "text": "Pushed the fix, retest shows 355.8 uF now.",
    "files": []
  },
  {
    "ts": "1784611201.017600",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Battery internal resistance reads 627.7 ohm on the new pack, 1.9 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1784653249.786237",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1776233395.401620",
    "text": "Attaching the updated numbers now.",
    "files": []
  },
  {
    "ts": "1784859640.866252",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "PDH main breaker is 508.1 A, sized for 486 A continuous draw from the drivetrain.",
    "files": []
  },
  {
    "ts": "1785274101.798370",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Ordered the S3-relay-40A for 34 USD, budget line still has 773.9 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1785361326.974256",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1779910328.915168",
    "text": "Ran it again, got 636.0 s this time, closer to spec.",
    "files": []
  },
  {
    "ts": "1785385806.275865",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Battery internal resistance reads 505.3 ohm on the new pack, 664 ohm on the spare.",
    "files": []
  },
  {
    "ts": "1785430222.174544",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Motor controller brownout threshold set to 709 V, current limit 349.34 A per module.",
    "files": []
  },
  {
    "ts": "1785471003.276630",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY03",
    "user_name": "Juno Marsh",
    "thread_ts": null,
    "text": "Instead of the CIM-2 we're routing through a 407 A breaker, quote came back at 175.63 USD.",
    "files": []
  },
  {
    "ts": "1785529184.464295",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Precharge sequence takes 790 ms to settle, relay closes 447.2 ms after enable.",
    "files": []
  },
  {
    "ts": "1785530328.198380",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Chassis weighed in at 255.29 kg on the shop scale, 216.1 kg under the estimate in the sim doc.",
    "files": []
  },
  {
    "ts": "1785606806.676175",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "PDH main breaker is 811.79 A, sized for 405.9 A continuous draw from the drivetrain. See arm-torque-review-final.xlsx.",
    "files": [
      "arm-torque-review-final.xlsx"
    ]
  },
  {
    "ts": "1785804276.618742",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1782092860.785281",
    "text": "Can we get 859 USD confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1785807938.326229",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": null,
    "text": "Chassis weighed in at 380.54 kg on the shop scale, 886 kg under the estimate in the sim doc.",
    "files": []
  },
  {
    "ts": "1785904429.728566",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Ordered the TE-ratchet-06 for 869.6 USD, budget line still has 771.8 USD left this quarter.",
    "files": []
  },
  {
    "ts": "1785932176.263639",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": null,
    "text": "Relay timer from enable to drive-ready is 611.87 ms, was 448 ms before the firmware bump.",
    "files": []
  },
  {
    "ts": "1786283116.517887",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY08",
    "user_name": "Leo Marsh",
    "thread_ts": "1785807938.326229",
    "text": "Agreed, going with 597.3 A for the design review.",
    "files": []
  },
  {
    "ts": "1786338889.884091",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "Updated: precharge resistor is now 714.9 ohm, supersedes the 125.67 ohm value from kickoff.",
    "files": []
  },
  {
    "ts": "1786339508.475397",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY06",
    "user_name": "Rowan Pike",
    "thread_ts": "1775915323.514317",
    "text": "Can we get 73.1 ms confirmed by Friday before we order?",
    "files": []
  },
  {
    "ts": "1786358876.898161",
    "channel": "C0WSY06",
    "channel_name": "ks4-general",
    "user": "U0WSY07",
    "user_name": "Priya Anand",
    "thread_ts": null,
    "text": "Motor controller brownout threshold set to 463 V, current limit 626.4 A per module.",
    "files": []
  },
  {
    "ts": "1786368257.694419",
    "channel": "C0WSY05",
    "channel_name": "ks4-drive",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": "1780797060.984301",
    "text": "Agreed, going with 177 mm for the design review.",
    "files": []
  },
  {
    "ts": "1786445478.988624",
    "channel": "C0WSY03",
    "channel_name": "ks4-firmware",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": null,
    "text": "Encoder counts per rev confirmed at 773.16, gear ratio still 840.9:1 same as last season.",
    "files": []
  },
  {
    "ts": "1786603342.764047",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY04",
    "user_name": "Milo Trent",
    "thread_ts": "1778604241.551463",
    "text": "Agreed, going with 681.0 USD for the design review.",
    "files": []
  },
  {
    "ts": "1786715663.796192",
    "channel": "C0WSY01",
    "channel_name": "ks4-electrical",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "Ambient in the electronics bay hit 705.9 deg C during the long auto test, fans kick on at 95 deg C.",
    "files": []
  },
  {
    "ts": "1786726144.404667",
    "channel": "C0WSY02",
    "channel_name": "ks4-mech",
    "user": "U0WSY05",
    "user_name": "Ines Calder",
    "thread_ts": null,
    "text": "Field wiring run is 558.7 mm gauge core, 498.52 mm insulation OD, matches the harness doc.",
    "files": []
  },
  {
    "ts": "1786745966.227118",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY02",
    "user_name": "Tam Holloway",
    "thread_ts": null,
    "text": "CAN bus utilization sitting around 645 percent at full tele-op load.",
    "files": []
  },
  {
    "ts": "1786804928.894755",
    "channel": "C0WSY04",
    "channel_name": "ks4-purchasing",
    "user": "U0WSY01",
    "user_name": "Dara Voss",
    "thread_ts": null,
    "text": "PDH main breaker is 375.0 A, sized for 189.4 A continuous draw from the drivetrain.",
    "files": []
  }
];
